repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
        - id: check-yaml
        #- id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-merge-conflict
        - id: debug-statements

-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    - id: flake8
      args: ["--ignore=CFQ002,E501,W503"] # CFQ002 -> many arguments in function | E501 -> corresponds to line too long | W503 -> line break before binary operator
      additional_dependencies: [ "flake8-print", "flake8-builtins", "flake8-functions==0.0.4" ]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: [ "--profile", "black", "--filter-files" ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]

-   repo: local
    hooks:
      - id: check-file-sizes-limit
        name: check-file-size-limit
        files: .*
        stages: [ commit ]
        language: system
        entry: ./.check_files.sh

-   repo: local
    hooks:
      - id: jupyter-nb-convert-to-markdown
        name: jupyter-nb-convert-to-markdown
        files: \.ipynb$
        stages: [commit]
        language: system
        types: ["file", "jupyter", "non-executable", "text"]
        entry: python -m nbconvert --to markdown *.ipynb

-   repo: local
    hooks:
      - id: git-add-jupyter-nb-markdown
        name: git-add-jupyter-nb-markdown
        stages: [post-commit]
        always_run: true
        language: system
        types: ["file", "markdown", "non-executable", "text"]
        entry: git add notebooks/\*.md
        pass_filenames: false

-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true